# Generated by Django 4.1.2 on 2022-10-17 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('api_key', models.CharField(max_length=20, unique=True)),
                ('check_type', models.CharField(choices=[('kitchen', 'kitchen'), ('client', 'client')], max_length=9)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kitchen', 'kitchen'), ('client', 'client')], max_length=9)),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], max_length=9)),
                ('pdf_file', models.FileField(upload_to='../media/pdf/')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_service.printer')),
            ],
        ),
    ]
